### ISSUE TITLE
synchronized-statement

### ISSUE THREAD

**Issue by deviator** [Pure-D/code-d#288]
Dlang have two form of `synchronized`:

```
SynchronizedStatement:
    synchronized ScopeStatement
    synchronized ( Expression ) ScopeStatement
```

https://dlang.org/spec/statement.html#SynchronizedStatement

But `syntaxes/d.json` and `syntaxes/d.yml` allows to use only form with brackets.

Without brackets syntax parser break highlight:

![](https://habrastorage.org/webt/ox/xt/jl/oxxtjljle1yxiv-mtpj9cmli-ay.png)

I think it can be fixed (works for me, but I not sure that it's good approach), if add pattern for `synchronized` to `d.json` and `d.yml`
```json
    "synchronized-statement": {
      "patterns": [
        {
          "match": "\\bsynchronized\\b",
          "name": "keyword.control.synchronized.d"
        },
        {
          "begin": "\\b(synchronized)\\b\\s*",
...
```
```yml
  synchronized-statement:
    patterns:
    - match: \bsynchronized\b
      name: keyword.control.synchronized.d
    - begin: \b(synchronized)\b\s*
      captures:
...
```
